boards/urls.py
from django.conf.urls import url

from . import views

app_name = 'boards'
urlpatterns = [
    url(r'^$', views.index , name='index'),
    url(r'^(?P<board_id>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^(?P<board_id>\d+)/topic(?P<topic_id>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'^(?P<board_id>\d+)/topic(?P<topic_id>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^(?P<board_id>\d+)/topic(?P<topic_id>\d+)/post(?P<post_pk>\d+)/edit/', views.PostUpdateView.as_view(), name='edit_post'),
]

djangoLearning/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from accounts.views import signup
from . import views

from django.contrib.auth import views as auth_views

# app_name = "home", for urls of the main,
# the app_name dont need to created
# cause Django engine consider from here to sub-urls.

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/', signup, name='signup'),
    url(r'^', include('accounts.urls'), name='accounts'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset/', include('password-reset.urls'), name='password-reset'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
    name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
    name='password_change_done'),
    url(r'^register/', include('user_auth.urls'), name='register'),
    url(r'^polls/', include('polls.urls'), name='polls'),
    url(r'^file-uploader/', include('file_uploader.urls'), name='file-uploader'),
    url(r'^pagination/', include('pagination.urls'), name='pagination'),
    url(r'^login/', include('login.urls'), name='login'),
    url(r'^boards/', include('boards.urls'), name='boards'),
    url(r'^admin/', admin.site.urls, name='admin'),
]

login/urls.py
from django.conf.urls import url

from . import views

app_name = "login"
urlpatterns = [
    url(r'^$', views.loginView, name='login'),
    url(r'^greeting/', views.formView, name='greeting'),
    url(r'^logout/', views.logoutView, name='logout'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = "polls"
urlpatterns = [
    # /polls/
    url(r'^$', views.index, name='index'),
    # url(r'^$', views.indexView.as_view(), name='index'),
    # /polls/details/<question_id>/
    url(r'^details/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<pk>[0-9]+)/$', views.detailView.as_view(), name='detail'),
    # /polls/<question_id>/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.resultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator
from django.utils.html import mark_safe
from markdown import markdown
import math
# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    def get_posts_count(self):
        return Post.objects.filter(topic__boards=self).count()
    def get_last_post(self):
        return Post.objects.filter(topic__boards=self).order_by('-created_at').first()

class Topic(models.Model):
    subject = models.CharField(max_length=250)
    last_updated = models.DateTimeField(auto_now_add=True)
    boards = models.ForeignKey(Board, related_name='topics')
    starter = models.ForeignKey(User, related_name='topics')
    views = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.subject

    def get_page_count(self):
        count = self.posts.count()
        pages = count/6
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()

        return count > 6

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count +1)

    def get_last_5_posts(self):
        return self.posts.order_by('-created_at')[:5]

class Post(models.Model):
    message = models.TextField(max_length=3500)
    topic = models.ForeignKey(Topic, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, related_name='+')
    def __str__(self):
        truncated_message=Truncator(self.message)
        return truncated_message.chars(30)
    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

boards/forms.py
from django import forms
from .models import Topic, Post

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': "What is on your mind?"}
        ),
        max_length=3500,
        help_text='The max length of the text is 3500'
    )

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

boards/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.http import HttpResponse, Http404
from django.db.models import Count
from django.contrib.auth.models import User
from .models import Board, Topic, Post
from django.views.generic import View, UpdateView, ListView
from .forms import NewTopicForm, PostForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.



def index(request):
    boards = Board.objects.all()

    return render(request, 'indexBoard.html', {'boards': boards})

def board_topics(request, board_id):
    try:
        board = Board.objects.get(pk=board_id)

    except Board.DoesNotExist:
        raise Http404("The board doesn't exist !!!")
    queryset = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)

    page = request.GET.get('page', 1)

    paginator = Paginator(queryset, 5)
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        topics = paginator.page(1)

    except EmptyPage:
        topics = paginator.page(paginator.num_pages)


    return render(request, 'topicsBoard.html', {'board': board, 'topics': topics})


@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.boards = board
            topic.starter = request.user
            topic.save()
            Post.objects.create(
                message = form.cleaned_data.get('message'),
                topic = topic,
                created_by = request.user
            )
            return redirect('boards:topic_posts', board_id=board.pk, topic_id=topic.pk)

    else:
        form = NewTopicForm()

    return render(request, 'newTopic.html', {'board': board, 'form': form})

# def topic_posts(request, board_id, topic_id):
#     topic = get_object_or_404(Topic, boards__pk=board_id, pk=topic_id)
#     topic.views += 1
#     topic.save()
#     return render(request, 'topic_posts.html', {'topic': topic})
#

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'topic_posts.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        session_key = 'view_topic_{}'.format(self.topic.pk)
        if not self.request.session.get(session_key, False):
            self.topic.views += 1
            self.topic.save()
            self.request.session[session_key] =True

        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, boards__pk=self.kwargs.get('board_id'), pk=self.kwargs.get('topic_id'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset

@login_required
def reply_topic(request, board_id, topic_id):
    topic = get_object_or_404(Topic, boards__pk=board_id, pk=topic_id)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            topic.last_updated = timezone.now()
            topic.save()

            topic_url = reverse('boards:topic_posts', kwargs={'board_id': board_id, 'topic_id': topic_id})
            topic_post_url = '{url}?page={page}'.format(
                url=topic_url,
                # id=post.pk,
                page=topic.get_page_count()

            )
            return redirect(topic_post_url)
    else:
        form = PostForm()

    return render(request, 'reply_topic.html', {'topic': topic, 'form': form})

@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ('message', )
    template_name = 'edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()
        return redirect('boards:topic_posts', board_id=post.topic.boards.pk, topic_id=post.topic.pk)

boards/templates/edit_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit post{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
        <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' post.topic.boards.pk %}">{{ post.topic.boards.name }}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' post.topic.boards.pk post.topic.pk %}">{{ post.topic.subject }}</a></li>
        <li class="breadcrumb-item active">Edit post</li>
    </ol>
        <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'boards:topic_posts' post.topic.boards.pk post.topic.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
        </form>
    </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/simplemde.min.js' %}"></script>
<script>
var simplemde = new SimpleMDE();
</script>
{% endblock %}

boards/templates/indexBoard.html
{% extends 'base.html' %}

{% block title %}Boards{% endblock %}

{#{% block breadcrumb %}#}
{#    <li class="breadcrumb-item active">Boards</li>#}
{#{% endblock %}#}

{% block body %}
    </br>
    </br>
    </br>
    </br>
    <div class="container">
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                  <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
                <td class="align-middle">{{ board.get_posts_count }}</td>
              <td class="align-middle">{{ board.topics.count }}</td>
              <td class="align-middle">
                  {% with post=board.get_last_post %}
                      {% if post %}
                        <small>
                        <a href="{% url 'boards:topic_posts' board.pk post.topic.pk %}">
                            By {{ post.created_by.username }} at {{ post.created_at }}
                        </a>
                        </small>
                      {% else %}
                        <small class="text-muted">
                        <em>No post yet.</em>
                        </small>
                      {% endif %}
                  {% endwith %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock %}

{#{% if boards %}#}
{##}
{#    {% for board in boards %}#}
{#        <a href="{% url 'boards:detail' board.id %}">{{ board.name }}</a>#}
{#        </br>#}
{#        <small style="color: #888">{{ board.description }}</small>#}
{#        </br>#}
{##}
{#        </br>#}
{#    {% endfor %}#}
{#{% else %}#}
{#    <p>There's no board !!!</p>#}
{#{% endif %}#}

boards/templates/newTopic.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Create a new topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a> </li>
    <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block body %}
    <div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a> </li>
        <li class="breadcrumb-item "><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
        <li class="breadcrumb-item active">New topic</li>
    </ol>

    <form method="post" novalidate>
        {% csrf_token %}
{#        <div class="form-group">#}
{#            <label for="id_subject">Subject</label>#}
{#            <input type="text" class="form-control" id="id_subject" name="subject">#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <label for="id_message">Message</label>#}
{#            <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>#}
{#        </div>#}

{#        {{ form.as_p }}#}

{#        {% for field in form %}#}
{#        <div class="form-group">#}
{#            {{ field.label_tag }}#}
{##}
{#            {% if form.is_bound %}#}
{#                {% if field.errors %}#}
{##}
{#                    {% render_field field class="form-control is-invalid" %}#}
{#                    {% for error in field.errors %}#}
{#                        <div class="invalid-feedback">#}
{#                        {{ error }}#}
{#                        </div>#}
{#                    {% endfor %}#}
{##}
{#                {% else %}#}
{#                    {% render_field field class="form-control is-valid" %}#}
{#                {% endif %}#}
{#            {% else %}#}
{#                {% render_field field class="form-control" %}#}
{#            {% endif %}#}
{##}
{#            {% if field.help_text %}#}
{#                <small class="form-text text-muted">#}
{#                    {{ field.help_text }}#}
{#                </small>#}
{#            {% endif %}#}
{##}
{#        </div>#}
{#        {% endfor %}#}

        {% include 'includes/form.html' %}

        <button type="submit" class="btn btn-success">Post</button>
    </form>
    </div>
{% endblock %}

boards/templates/reply_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Reply{% endblock %}

{% block body %}

    <div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Boards</a></li>
        <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.boards.pk %}">{{ topic.boards.name }}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' topic.boards.pk topic.pk %}">{{ topic.subject }}</a></li>
        <li class="breadcrumb-item active">Post a reply</li>
    </ol>


  <form method="post" class="mb-4">
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post a reply</button>
  </form>

  {% for post in topic.get_last_5_posts %}
    <div class="card mb-2">
      <div class="card-body p-3">
        <div class="row mb-3">
          <div class="col-6">
            <strong class="text-muted">{{ post.created_by.username }}</strong>
          </div>
          <div class="col-6 text-right">
            <small class="text-muted">{{ post.created_at }}</small>
          </div>
        </div>
        {{ post.get_message_as_markdown }}
      </div>
    </div>
  {% endfor %}

{% endblock %}

boards/templates/topic_posts.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load gravatar %}

{% block title %}{{ topic.subject }}{% endblock %}


{% block body %}
    <div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a></li>
        <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.boards.pk %}">{{ topic.boards.name }}</a></li>
        <li class="breadcrumb-item active">{{ topic.subject }}</li>
    </ol>
        <div class="mb-4">
        <a href="{% url 'boards:reply_topic' topic.boards.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
        </div>

      {% for post in posts %}
        <div id="{{ post.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
        {% if forloop.first %}
            <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
        {% endif %}
        <div class="card-body p-3">
            <div class="row">
            <div class="col-2">
{#                <img src="{% static 'img/avatar.png' %}" alt="{{ post.created_by.username }}" class="w-100 rounded">#}
                <img src="{{ post.created_by|gravatar }}" alt="{{ post.created_by.username }}" class="w-100 rounded">
                <small>Posts: {{ post.created_by.posts.count }}</small>
            </div>
            <div class="col-10">
                <div class="row mb-3">
                <div class="col-6">
                    <strong class="text-muted">{{ post.created_by.username }}</strong>
                </div>
                <div class="col-6 text-right">
                    <small class="text-muted">{{ post.created_at }}</small>
                </div>
                </div>
                {{ post.get_message_as_markdown }}
                {% if post.created_by == user %}
                <div class="mt-3">
                    <a href="{% url 'boards:edit_post' post.topic.boards.pk post.topic.pk post.pk %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                </div>
                {% endif %}
            </div>
            </div>
        </div>
        </div>
      {% endfor %}
    {% include 'includes/postsPagination.html' %}
{% endblock %}

boards/templates/topicsBoard.html
{% extends 'base.html' %}
{% load humanize %}

{%  block title %}
    {{ board.name }} - Djang Board
{% endblock %}



{#{% block breadcrumb %}#}
{#    <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a> </li>#}
{#    <li class="breadcrumb-item active">{{ board.name }}</li>#}
{#{% endblock %}#}

{% block body %}
    <div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'boards:index' %}">Boards</a> </li>
        <li class="breadcrumb-item active">{{ board.name }}</li>
    </ol>

    <div class="mb-4">
    <a href="{% url 'boards:new_topic' board.pk %}" class="btn btn-success">Create new topic</a>
    </div>

    <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in topics %}
          {% url 'boards:topic_posts' board.pk topic.pk as topic_url %}
        <tr>
        <td>
            <p class="mb-0">
                <a href="{{ topic_url }}">{{ topic.subject }}</a>
            </p>
            <small class="text-muted">
                Pages:
                {% for i in topic.get_page_range %}
                    <a href="{{ topic_url }}?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% if topic.has_many_pages %}
                ... <a href="{{ topic_url }}?page={{ topic.get_page_count }}">Last page</a>
            {% endif %}
            </small>
        </td>
{#            <td><a href="{% url 'boards:topic_posts' board.pk topic.pk %}">{{ topic.subject }}</a></td>#}
          <td class="align-middle">{{ topic.starter.username }}</td>
          <td class="align-middle">{{ topic.replies }}</td>
          <td class="align-middle">{{ topic.views }}</td>
          <td class="align-middle">{{ topic.last_updated | naturaltime }}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
    {% if topics.has_other_pages %}
    <nav aria-label="Topics pagination" class="mb-4">
        <ul class="pagination">
            {% if topics.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ topics.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previvous</span>
            </li>
            {% endif %}

        {% for page_num in topics.paginator.page_range %}
        {% if topics.number == page_num %}
        <li class="page-item active">
            <span class="page-link">
                {{ page_num }}<span class="sr-only">(current)</span>
            </span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if topics.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ topics.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}
        </ul>
    </nav>
    {% endif %}
    </div>
{% endblock %}