accounts/urls.py
from django.conf.urls import url

from . import views

app_name='accounts'

urlpatterns = [
    url(r'^settings/account/', views.UserUpdateView.as_view(), name='my_account'),
]

boards/urls.py
from django.conf.urls import url

from . import views

app_name = 'boards'
urlpatterns = [
    url(r'^$', views.index , name='index'),
    url(r'^(?P<board_id>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^(?P<board_id>\d+)/topic(?P<topic_id>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'^(?P<board_id>\d+)/topic(?P<topic_id>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^(?P<board_id>\d+)/topic(?P<topic_id>\d+)/post(?P<post_pk>\d+)/edit/', views.PostUpdateView.as_view(), name='edit_post'),
]

djangoLearning/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from accounts.views import signup
from . import views

from django.contrib.auth import views as auth_views

# app_name = "home", for urls of the main,
# the app_name dont need to created
# cause Django engine consider from here to sub-urls.

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/', signup, name='signup'),
    url(r'^', include('accounts.urls'), name='accounts'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset/', include('password-reset.urls'), name='password-reset'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
    name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
    name='password_change_done'),
    url(r'^register/', include('user_auth.urls'), name='register'),
    url(r'^polls/', include('polls.urls'), name='polls'),
    url(r'^file-uploader/', include('file_uploader.urls'), name='file-uploader'),
    url(r'^pagination/', include('pagination.urls'), name='pagination'),
    url(r'^login/', include('login.urls'), name='login'),
    url(r'^boards/', include('boards.urls'), name='boards'),
    url(r'^admin/', admin.site.urls, name='admin'),
]

login/urls.py
from django.conf.urls import url

from . import views

app_name = "login"
urlpatterns = [
    url(r'^$', views.loginView, name='login'),
    url(r'^greeting/', views.formView, name='greeting'),
    url(r'^logout/', views.logoutView, name='logout'),
]

pagination/urls.py
from django.conf.urls import url
from . import views

app_name = 'pagination'
urlpatterns = [
    url(r'$', views.listing, name='list'),
]

password-reset/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import templates
from . import views

app_name='password-reset'

urlpatterns = [
    url(r'^$', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
    ), name='reset'),
    url(r'^done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='done'),
    url(r'^(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}/$)',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='confirm'),
    url(r'^complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='complete'),

]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = "polls"
urlpatterns = [
    # /polls/
    url(r'^$', views.index, name='index'),
    # url(r'^$', views.indexView.as_view(), name='index'),
    # /polls/details/<question_id>/
    url(r'^details/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<pk>[0-9]+)/$', views.detailView.as_view(), name='detail'),
    # /polls/<question_id>/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.resultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

login/models.py
from django.db import models

# Create your models here.

class user(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

password-reset/models.py
from django.db import models

# Create your models here.

login/forms.py
# from django import forms
# from django.core import validators
#
# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=100, validators=[validators.validate_slug])
#     password = forms.CharField(widget=forms.PasswordInput())
#


from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="username",max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

login/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
# Create your views here.
from .forms import LoginForm
from .models import user

# def formView(request):
#     if request.session.has_key('username'):
#         username = request.session['username']
#         return render(request, 'loggedin.html', {'username': username})
#     else:
#         return render(request, 'login.html', {})


def loginView(request):
    if request.method == "POST":
        # username = "Wrong username or password"
        MyLoginForm = LoginForm(request.POST)
        if MyLoginForm.is_valid():
            try:
                u = user.objects.get(username=MyLoginForm.cleaned_data['username'])

            except:
                warning = 1
                return render(request, 'login.html', {'waring': warning})

            if MyLoginForm.cleaned_data['password'] == u.password:
                username = u.username
                request.session['username'] = username
                request.session.set_expiry(15);
                return HttpResponseRedirect(reverse('login:greeting'))

            else:
                warning = 1
                return render(request, 'login.html', {'waring': warning})


    else:
        return render(request, 'login.html', {})
        #     if MyLoginForm.cleaned_data['username'] == :
        #         if MyLoginForm.cleaned_data['password'] == '123':
        #             username = MyLoginForm.cleaned_data['username']
        #             request.session['username'] = username
        #             request.session.set_expiry(15);
        # return render(request, 'loggedin.html', {'username': username})

        # MyLoginForm = LoginForm()
        # return render(request, 'login.html', {})
        # formView(request)

def formView(request):
    if request.session.has_key('username'):
        username = request.session['username']
        return render(request, 'loggedin.html', {'username': username})
    else:
        return HttpResponseRedirect(reverse('login:login'))

def logoutView(request):
    try:
        del request.session['username']
    except:
        pass
    return HttpResponse("Good bye!")

password-reset/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{%  load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
</head>
<body>

{% block top %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">VKing34</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-label="userMenu">
                        <a class="dropdown-item" href="{% url 'accounts:my_account' %}">My account</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                </li>
                </ul>
            {% else %}
                <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
                </form>
            {% endif %}
        </div>
    </div>
    </nav>
{% endblock top %}

{% block pre %}
{% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'boards:index' %}">Djang Boards</a>
        </div>
    </nav>
    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}
            {% endblock %}
        </ol>
            {% block content %}
            {% endblock %}
    </div>

{% endblock body %}

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center logo my-4">
        <a href="{% url 'index' %}">VKing34</a>
    </h1>
    {% block content %}
    {% endblock content %}
</div>
{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% load humanize %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{#{% block top %}#}
{##}
{#    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">#}
{#    <div class="container">#}
{#      <a class="navbar-brand" href="{% url 'index' %}">VKing34</a>#}
{#      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">#}
{#        <span class="navbar-toggler-icon"></span>#}
{#      </button>#}
{#      <div class="collapse navbar-collapse" id="mainMenu">#}
{#        <ul class="navbar-nav ml-auto">#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">{{ user.username }}</a>#}
{#          </li>#}
{#        </ul>#}
{#      </div>#}
{#    </div>#}
{#    </nav>#}
{##}
{#{% endblock top %}#}

{% block pre %}

<h1>
Welcome to my website !
</h1>
<p>This is website created by VKing34</p>
</br>
<a href="{% url 'polls:index' %}">Click here</a><a> to get some polls.</a>
</br>
</br>
<a href="{% url 'fuloader:fileUploader' %}">Upload Files</a>
</br>
</br>
<a href="{% url 'pagination:list' %}">Paginatio</a>
</br>
</br>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}


{% block content %}
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">{{ board.get_posts_count }}</td>
              <td class="align-middle">{{ board.topics.count }}</td>
              <td class="align-middle">
                  {% with post=board.get_last_post %}
                      {% if post %}
                        <small>
                        <a href="{% url 'boards:topic_posts' board.pk post.topic.pk %}">
                            {{ post.created_at|naturaltime }} by {{ post.created_by.username }}
                        </a>
                        </small>
                      {% else %}
                        <small class="text-muted">
                        <em>No post yet.</em>
                        </small>
                      {% endif %}
                  {% endwith %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Log in</h3>
                <form method="post" novalidate>
                    {% csrf_token %}
{#                    <input type="hidden" name="next" value="{{ next }}">#}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-primary btn-block">Log in</button>
                </form>
            </div>
            <div class="card-footer text-muted text-center">
                Create a new account? <a href="{% url 'signup' %}">Sign up</a>
            </div>
        </div>
        <div class="text-center py-2">
            <small>
                <a href="#" class="text-muted">Forgot your password?</a>
            </small>
        </div>
    </div>
    </div>
{% endblock %}

templates/my_account.html
{% extends 'base.html' %}

{% block title %}My account{% endblock %}

{% block body %}
    <div class="container">
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active" >My account</li>
    </ol>
        <div class="row center">
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-success">Save changes</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}


{% block body %}

    <div class="container">
        <ol class="breadcrumb my-4">
            Change password
        </ol>
        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-success">Change password</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}Successful{% endblock %}


{% block body %}

    <div class="container">
        <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
            <li class="breadcrumb-item active">Success</li>
        </ol>
            <div class="alert alert-success" role="alert">
                <strong>Success!</strong> Your password has been changed!
            </div>
            <a href="{% url 'index' %}" class="btn btn-secondary">Return to home page</a>
    </div>

{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block title %}Successful{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
{% if validlink %}
Change password for {{ form.username }}
{% else %}
Reset your password
{% endif %}
{% endblock %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="card">
            <div class="card-body">
                {% if validlink %}
                <h3 class="card-title">Change password for {{ form.username }}</h3>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-success btn-block">Change password</button>

                </form>
                {% else %}
                <h3 class="card-title">Reset your password</h3>
                <div class="alert alert-danger" role="alert">
                    This link you have just clicked is invalid.
                    Please try again.
                </div>
                <a href="{% url 'password-reset:reset' %}" class="btn btn-secondary btn-block">
                    Request a new password reset link
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Reset your password</h3>
                <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
                <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password-reset:confirm' uidb64=uid token=token %}

In case you forgot your username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

VKing34

templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up{% endblock %}



{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}